[tasks.watch]
command = "cargo"
args = ["leptos", "watch"]
cwd = "taskapp"
workspace = false 

[tasks.fmt]
command = "leptosfmt"
args = ["./**/*.rs"]
workspace = false

[tasks.services]
description = "Start PostgreSQL v16 container for local development"
workspace = false
command = "docker"
args= ["compose", "up", "-d"]

[tasks.services-stop]
description = "Stop and remove PostgreSQL container"
workspace = false
command = "docker"
args = ["compose", "down"]

[tasks.psql]
description = "Connect to running PSQL instance"
workspace = false
command = "psql"
args = ["-h", "localhost", "-p", "5432", "-U", "taskapp", "-d", "taskapp"]
